import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding campaigns and measurements...')

  // Get operator IDs
  const orange = await prisma.operator.findFirst({ where: { code: 'ORG' } })
  const mtn = await prisma.operator.findFirst({ where: { code: 'MTN' } })
  const celcom = await prisma.operator.findFirst({ where: { code: 'CEL' } })
  const guinetel = await prisma.operator.findFirst({ where: { code: 'GTEL' } })

  if (!orange || !mtn || !celcom) {
    console.error('Missing operators, aborting seed')
    return
  }

  // Get admin user
  const admin = await prisma.user.findFirst({ where: { role: 'admin' } })

  // Create completed campaign
  const campaign1 = await prisma.campaign.upsert({
    where: { reference: 'CAMP-2025-001' },
    update: {},
    create: {
      reference: 'CAMP-2025-001',
      name: 'Campagne Nationale QoS Q1 2025',
      description: 'Audit de la couverture et de la qualité de service des réseaux mobiles et FAI - Premier trimestre 2025',
      type: 'combined',
      status: 'completed',
      startDate: new Date('2025-01-15'),
      endDate: new Date('2025-03-30'),
      regions: 'CK,KD,KN,BK,MM',
      localities: '46',
      technologies: '2G,3G,4G',
      services: 'voix,sms,data',
      teamSize: 8,
      equipment: 'TEMS Pocket, TEMS Paragon, TEMS Discovery',
      totalTests: 2850,
      conformRate: 72.5,
      createdById: admin?.id,
    },
  })

  // Create in-progress campaign
  const campaign2 = await prisma.campaign.upsert({
    where: { reference: 'CAMP-2025-002' },
    update: {},
    create: {
      reference: 'CAMP-2025-002',
      name: 'Drive Test Conakry Q2 2025',
      description: 'Tests de couverture et qualité de service sur la zone de Conakry - Deuxième trimestre 2025',
      type: 'drive_test',
      status: 'in_progress',
      startDate: new Date('2025-04-01'),
      endDate: null,
      regions: 'CK',
      localities: '5',
      technologies: '3G,4G',
      services: 'voix,data',
      teamSize: 4,
      equipment: 'TEMS Pocket, Nemo Handy',
      totalTests: 0,
      createdById: admin?.id,
    },
  })

  // Create planned campaign
  const campaign3 = await prisma.campaign.upsert({
    where: { reference: 'CAMP-2025-003' },
    update: {},
    create: {
      reference: 'CAMP-2025-003',
      name: 'Walk Test Zones Rurales Q3 2025',
      description: 'Évaluation de la couverture en zones rurales - Troisième trimestre 2025',
      type: 'walk_test',
      status: 'planned',
      startDate: null,
      endDate: null,
      regions: 'KD,BK,MM',
      localities: '12',
      technologies: '2G,3G',
      services: 'voix,sms',
      teamSize: 6,
      equipment: 'TEMS Pocket',
      totalTests: 0,
      createdById: admin?.id,
    },
  })

  console.log(`Created 3 campaigns`)

  // Create measurements for campaign1 - Orange 4G Conakry
  const measurements = [
    // Orange measurements
    {
      campaignId: campaign1.id,
      operatorId: orange.id,
      region: 'Conakry',
      locality: 'Kaloum',
      testType: 'drive_test',
      technology: '4G',
      callAttempted: 150,
      callSuccess: 142,
      callDropped: 3,
      callSetupTime: 3.2,
      smsSent: 100,
      smsSuccess: 97,
      smsDelay: 4.1,
      downloadSpeed: 28.5,
      uploadSpeed: 12.3,
      latency: 35,
      packetLoss: 0.5,
      webPageLoadTime: 3.2,
      videoStreamingScore: 4.2,
      downloadSuccessRate: 96.5,
      signalStrength: -72,
      coverageLevel: 'good',
      latitude: 9.5092,
      longitude: -13.7122,
      measuredAt: new Date('2025-02-10T10:30:00'),
      isConform: true,
    },
    {
      campaignId: campaign1.id,
      operatorId: orange.id,
      region: 'Conakry',
      locality: 'Dixinn',
      testType: 'walk_test',
      technology: '3G',
      callAttempted: 80,
      callSuccess: 72,
      callDropped: 5,
      callSetupTime: 5.1,
      smsSent: 60,
      smsSuccess: 55,
      smsDelay: 6.2,
      downloadSpeed: 8.4,
      uploadSpeed: 3.2,
      latency: 68,
      packetLoss: 1.8,
      webPageLoadTime: 7.5,
      videoStreamingScore: 2.8,
      downloadSuccessRate: 88.0,
      signalStrength: -82,
      coverageLevel: 'fair',
      latitude: 9.5350,
      longitude: -13.6877,
      measuredAt: new Date('2025-02-12T14:00:00'),
      isConform: false,
    },
    {
      campaignId: campaign1.id,
      operatorId: orange.id,
      region: 'Kankan',
      locality: 'Kankan Centre',
      testType: 'fixed_test',
      technology: '2G',
      callAttempted: 60,
      callSuccess: 48,
      callDropped: 8,
      callSetupTime: 7.8,
      smsSent: 40,
      smsSuccess: 34,
      smsDelay: 8.5,
      downloadSpeed: 0.2,
      uploadSpeed: 0.1,
      latency: 180,
      packetLoss: 4.2,
      webPageLoadTime: 25.0,
      videoStreamingScore: 1.0,
      downloadSuccessRate: 60.0,
      signalStrength: -95,
      coverageLevel: 'poor',
      latitude: 10.3828,
      longitude: -9.3050,
      measuredAt: new Date('2025-02-20T09:00:00'),
      isConform: false,
    },
    // MTN measurements
    {
      campaignId: campaign1.id,
      operatorId: mtn.id,
      region: 'Conakry',
      locality: 'Kaloum',
      testType: 'drive_test',
      technology: '4G',
      callAttempted: 150,
      callSuccess: 135,
      callDropped: 6,
      callSetupTime: 4.1,
      smsSent: 100,
      smsSuccess: 93,
      smsDelay: 5.0,
      downloadSpeed: 22.1,
      uploadSpeed: 9.8,
      latency: 48,
      packetLoss: 1.0,
      webPageLoadTime: 4.5,
      videoStreamingScore: 3.5,
      downloadSuccessRate: 92.0,
      signalStrength: -78,
      coverageLevel: 'good',
      latitude: 9.5092,
      longitude: -13.7122,
      measuredAt: new Date('2025-02-11T10:30:00'),
      isConform: true,
    },
    {
      campaignId: campaign1.id,
      operatorId: mtn.id,
      region: 'Conakry',
      locality: 'Matam',
      testType: 'drive_test',
      technology: '3G',
      callAttempted: 120,
      callSuccess: 100,
      callDropped: 8,
      callSetupTime: 6.5,
      smsSent: 80,
      smsSuccess: 72,
      smsDelay: 7.3,
      downloadSpeed: 5.2,
      uploadSpeed: 2.1,
      latency: 95,
      packetLoss: 2.5,
      webPageLoadTime: 10.2,
      videoStreamingScore: 2.2,
      downloadSuccessRate: 80.0,
      signalStrength: -88,
      coverageLevel: 'fair',
      latitude: 9.5485,
      longitude: -13.6785,
      measuredAt: new Date('2025-02-13T11:00:00'),
      isConform: false,
    },
    {
      campaignId: campaign1.id,
      operatorId: mtn.id,
      region: 'Kindia',
      locality: 'Kindia Centre',
      testType: 'walk_test',
      technology: '2G',
      callAttempted: 50,
      callSuccess: 38,
      callDropped: 7,
      callSetupTime: 9.2,
      smsSent: 30,
      smsSuccess: 24,
      smsDelay: 10.1,
      downloadSpeed: 0.1,
      uploadSpeed: 0.05,
      latency: 220,
      packetLoss: 5.8,
      webPageLoadTime: 35.0,
      videoStreamingScore: 1.0,
      downloadSuccessRate: 55.0,
      signalStrength: -100,
      coverageLevel: 'poor',
      latitude: 10.0581,
      longitude: -12.8605,
      measuredAt: new Date('2025-02-25T09:00:00'),
      isConform: false,
    },
    // Celcom measurements
    {
      campaignId: campaign1.id,
      operatorId: celcom.id,
      region: 'Conakry',
      locality: 'Kaloum',
      testType: 'drive_test',
      technology: '4G',
      callAttempted: 140,
      callSuccess: 122,
      callDropped: 8,
      callSetupTime: 4.8,
      smsSent: 90,
      smsSuccess: 82,
      smsDelay: 5.5,
      downloadSpeed: 18.3,
      uploadSpeed: 7.5,
      latency: 62,
      packetLoss: 1.5,
      webPageLoadTime: 5.2,
      videoStreamingScore: 3.0,
      downloadSuccessRate: 87.0,
      signalStrength: -80,
      coverageLevel: 'good',
      latitude: 9.5092,
      longitude: -13.7122,
      measuredAt: new Date('2025-02-11T14:00:00'),
      isConform: true,
    },
    {
      campaignId: campaign1.id,
      operatorId: celcom.id,
      region: 'Boké',
      locality: 'Boké Centre',
      testType: 'walk_test',
      technology: '3G',
      callAttempted: 70,
      callSuccess: 52,
      callDropped: 9,
      callSetupTime: 8.2,
      smsSent: 50,
      smsSuccess: 40,
      smsDelay: 9.5,
      downloadSpeed: 3.1,
      uploadSpeed: 1.2,
      latency: 120,
      packetLoss: 3.8,
      webPageLoadTime: 15.0,
      videoStreamingScore: 1.5,
      downloadSuccessRate: 72.0,
      signalStrength: -92,
      coverageLevel: 'poor',
      latitude: 10.9315,
      longitude: -14.2950,
      measuredAt: new Date('2025-03-05T10:00:00'),
      isConform: false,
    },
    // Guinetel (FAI) measurements
    {
      campaignId: campaign1.id,
      operatorId: guinetel?.id,
      region: 'Conakry',
      locality: 'Dixinn',
      testType: 'fixed_test',
      technology: 'fixe',
      callAttempted: null,
      callSuccess: null,
      callDropped: null,
      callSetupTime: null,
      smsSent: null,
      smsSuccess: null,
      smsDelay: null,
      downloadSpeed: 12.0,
      uploadSpeed: 4.5,
      latency: 55,
      packetLoss: 1.2,
      webPageLoadTime: 6.0,
      videoStreamingScore: 2.5,
      downloadSuccessRate: 82.0,
      signalStrength: null,
      coverageLevel: 'fair',
      latitude: 9.5350,
      longitude: -13.6877,
      measuredAt: new Date('2025-02-15T10:00:00'),
      isConform: false,
    },
  ]

  for (const m of measurements) {
    await prisma.measurement.create({ data: m })
  }

  console.log(`Created ${measurements.length} measurements`)
  console.log('Seed completed!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
